spring:
  # Datasource
  datasource:
    url: jdbc:postgresql://localhost:5432/workout-tracker-db
    username: user
    password: 1234
  # JPA
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate